### PR TITLE
Updated Tribler 7 links and screenshot images

### PR DESCRIPTION
**Pull request by xoriole**
- Updated Tribler 7 links and screenshot images. 
- Disabled user voice plugin
- Renamed getting started to how it works in navigation bar

### CODE REVIEW

**Comment by qstokkink** [comment]
Don't forget to alter the text on the FAQ page 👍

**Comment by devos50** [comment]
@qstokkink I'm doing a major refactor of the FAQ as we speak 👍

**Comment by qstokkink** [comment]
@devos50 Will this be in a separate PR?

**Comment by devos50** [comment]
@qstokkink yes

**Comment by qstokkink** [comment]
The `4` pointer will be explained in another PR right?

**Pull request merged**
