### PR TITLE
Updated to dark theme of Tribler 7.0

### PR DESCRIPTION
**Pull request by qstokkink**
This changes the website to the new dark theme. Fixes Tribler/tribler#2998.

### CODE REVIEW

**Comment by qstokkink** [comment]
@devos50 Could you have a look at this?

**Comment by qstokkink** [comment]
@synctext @devos50 Front page screenshot 👍 / 👎 ?

screenshot_home_page_torrents

**Comment by devos50** [comment]
@qstokkink looks fine, however, the category label does not look very good with the screenshot. Maybe we should move the category label to the light-gray subtitle?

**Comment by qstokkink** [comment]
@devos50 Like this? Also did one without categories:
screenshot_home_page_torrents_nocat
screenshot_home_page_torrents_recat

**Comment by synctext** [comment]
Looks good!

**Pull request merged**
